name: Share
description: The mobile application to manage the Share pattern

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  animated_bottom_navigation_bar: ^0.1.2+2
  spring_button: ^1.0.13
  flutter_custom_clippers: ^1.1.1
  udp: ^3.0.3
  luavm: ^0.1.1
  flutter_svg: ^0.17.0
  flutter_spinkit: ^4.1.2+1
  wave: ^0.0.8
  flutter_echarts: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
